name: Hello world workflow

on:
  push:
    branches:
      - main:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: unbuntu-latest
    steps:
      - use: actions/checkout@v2
      - name: hello world
        run: echo "Hello World!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world!"
        shell: bash
