name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted ,  Linux , X64 ,  label-40 ]
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello World!"
        shell: bash
  goodbye:
    runs-on: [self-hosted ,  Linux , X64 ,  label-40 ]
    steps:
      - name: goodbye world
        run: echo "Goodbye world!"
        shell: bash
